### ISSUE TITLE
Make /ticket threads private

### ISSUE THREAD

**Issue by Pixe1Atom** [Enroute-Transport/Aometry#12]
Threads should only be viewable by the threads creator and Metrol, but currently, anyone can view the thread/tickets. If someone is trying to report a user, that reported user can view the thread. Are there any permission changes that could fix this?

**Comment by finneh4249** [comment]
This is possible but it’s a little challenging to make work as private threads require nitro level 2 and a non-private thread won’t be made if a private thread is requested
I’ll have a look into getting it to work, should be a simple if statement at the top of the code but it might break something, we’ll see!

**Comment by Pixe1Atom** [comment]
I'm guessing threads are better then the old channel system? If it requires Boosting level 2, as you said, just have the threads public, then private messages can just be sent via DMs.

**Comment by finneh4249** [comment]
There's a few options that I can think of for tickets.
Either:
Scrap using threads all together and use a private channel (this is the easiest option)
Utilise a guild check and use a private channel if not level 2
Utilise a guild check and use a public thread if not level 2

**Comment by Pixe1Atom** [comment]
Can threads have thread specific permissions? If yes, then private channels and private thread with Nitro level 2 are the best choices. If no, then just use private channels.

**Comment by finneh4249** [comment]
I'll have a look into it but I definitely agree that that's probably the best way to go.
A planned feature for the bot is to remove the sent thread message once the thread is created, which may alleviate some but not all of the issue as members of the public could still read and/or join the threads

**Comment by Pixe1Atom** [comment]
'A planned feature for the bot is to remove the sent thread message once the thread is created' Does this mean the threads would be private and not have a join link?
