### ISSUE TITLE
warn command

### ISSUE THREAD

**Issue by SoundWavez97** [Enroute-Transport/Aometry#15]
warn command bugs
- warn clear doesnt work,
- running warn remove then trying warn check it doesnt say user has no warns but just send a totpe saying WARNINGS...to reproduce warn someone then rekove it then run warn check command,
- warn add shows undefined as to who warned user

**Comment by finneh4249** [comment]
Hey thanks for opening this issue.
I wasn’t aware of these specific issues, however, in my latest commit to the canary branch (not currently pushed) I disabled the existing moderation module as im replacing it with a brand new moderation module. This can be found on the project map
https://github.com/Enroute-Transport/Aometry/projects/1#card-70241011
