### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SoundWavez97** [Enroute-Transport/Aometry#16]
multi guild ticket system with buttons and and advanced moderation system where its all in one command called "modpanel- which has buttons of ban,tempban,tempmute,mute,kick and an a button to the success message that has undo hutton like u do !ban @user and the bot sends successfully banned ${thatuser} with and undo button that auto disabled after 1min

**Comment by finneh4249** [comment]
Added to project map, thanks for your request, if possible could you provide screenshots or an in-depth explanation of the proposed solution?

**Comment by finneh4249** [comment]
Merged with Issue #26
